# Copyright 2020 SkillTree
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Cross-browser E2E Tests

#on:
#  schedule:
#    - cron: '0 5 * * *'
#  workflow_dispatch:

# temp, for branch testing
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitlab-ci.yml'

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          paths_ignore: '["**/README.md"]'

  build-skills-service-for-ui-tests:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - uses: actions/setup-java@v1
        with:
          java-version: '11.X.X' # The JDK version to make available on the path.

      - name: Print Versions
        run: |
          mvn --version
          java -version

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build skills-service
        run: mvn --batch-mode install -DskipTests

      - name: upload service jar
        uses: actions/upload-artifact@v2
        with:
          name: service jar
          path: ./service/target/*.jar

  ui-cross-browser-h2:
    runs-on: ubuntu-latest
    needs: [build-skills-service-for-ui-tests]
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 4 copies of the current job in parallel
        containers: [1, 2, 3, 4]

    steps:
    - name: Install Emoji Support
      run: sudo apt-get install fonts-noto-color-emoji

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - uses: actions/setup-java@v1
      with:
        java-version: '11.X.X' # The JDK version to make available on the path.

    - name: Print Versions
      run: |
        mvn --version
        java -version

    - uses: actions/download-artifact@v2
      with:
        name: service jar
        path: ./service/target/

    - name: 'BrowserStack Env Setup'
      uses: 'browserstack/github-actions/setup-env@master'
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    - name: 'Start BrowserStackLocal Tunnel'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: 'start'
        local-logging-level: 'all-logs'
        local-identifier: 'random'

    - name: Prep Services for Cypress tests
      run: |
        cd e2e-tests
        npm install -g browserstack-cypress-cli
        npm install
        npm run cyServices:start
        cd ..

    - name: Run Cypress tests
      run: |
        cd e2e-tests
        browserstack-cypress run --sync --browserstack.localIdentifier=${{env.BROWSERSTACK_LOCAL_IDENTIFIER}}

    - name: upload result artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: CI result artifacts ${{ matrix.container }}
        path: |
          ./e2e-tests/logs
          ./e2e-tests/cypress/snapshots/**/**/__diff_output__/*.png
          ./e2e-tests/cypress/snapshots/**/__diff_output__/*.png

    - name: 'Stop BrowserStackLocal'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
        local-testing: 'stop'

